### ISSUE TITLE
Time stamp/date for sent mail

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/SatanicBot#122] opened 2017-06-03 23:19 UTC
This would add some context and be helpful. It wouldn't be super-useful since different people use different time zones and couldn't get much from UTC±00:00 (time zones command anybody?) but it could help.

**Comment by elifoster** [comment] 2017-06-30 16:43
Duplicate of #116

**Comment by elifoster** [comment] 2017-06-30 16:43
Never mind, it actually isn't a duplicate. Misunderstood the two issues.

**Closed** 2017-06-30 17:22 UTC
Labels: enhancement, irc, mail, prio:low
